apiVersion: v1
kind: Service
metadata:
  name: ray-head-nodeport
spec:
  type: NodePort
  selector:
    ray-head: "true"   # my custom label
  ports:
    - port: 8265
      targetPort: 8265
      nodePort: 30081
