version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  uppercase-string:
    lang: python3-http
    handler: ./uppercase-string
    image: amiralikazi/uppercase-string:latest

